### ISSUE TITLE
Use `standard_normal` instead of `normal(0, 1)` function.

### ISSUE THREAD

**Issue by zoj613** [aesara-devs/aehmc#11]
At https://github.com/aesara-devs/aehmc/blob/87b0c4d20c276d191522132c1f3f00fec70239b1/aehmc/metrics.py#L28

`normal(0, 1)` could be replaced with `standard_normal`. This change could make it easier to read without thinking about the input values.

**Comment by rlouf** [comment]
I could not find `standard_normal` in the [aesara repo](https://github.com/aesara-devs/aesara/blob/main/aesara/tensor/random/basic.py). Where did you find it?

The default values for `loc` and `scale ` here are respectively `0` and `1`, but I am not sure it would improve the code to only specify the size.

**Comment by zoj613** [comment]
> I could not find `standard_normal` in the [aesara repo](https://github.com/aesara-devs/aesara/blob/main/aesara/tensor/random/basic.py?rgh-link-date=2021-07-19T15%3A33%3A11Z). Where did you find it?
> 
> The default values for `loc` and `scale ` here are respectively `0` and `1`, but I am not sure it would improve the code to only specify the size.

https://aesara.readthedocs.io/en/latest/library/tensor/random/basic.html?highlight=RandomStream#aesara.tensor.random.RandomStream claims to behave like `np.random.RandomState`, so I assumed this function is exposed. Let me close this then.

**Comment by brandonwillard** [comment]
@zoj613, feel free to add an issue in Aesara for that.

**Comment by zoj613** [comment]
> @zoj613, feel free to add an issue in Aesara for that.

Done.
