### ISSUE TITLE
Change `at.inv` to `at.reciprocal`

### ISSUE THREAD

**Issue by zoj613** [aesara-devs/aehmc#12]
Is there a reason why `at.inv` is used instead of `1 / inverse_mass_matrix` when inverse_mass_matrix is 1-dimensional? 
https://github.com/aesara-devs/aehmc/blob/87b0c4d20c276d191522132c1f3f00fec70239b1/aehmc/metrics.py#L15

Does it have an advantage over the latter? Apologies if this is obvious to some but I was confused by the line when I read it.

**Comment by brandonwillard** [comment]
`at.inv` is the old, deprecated name for `at.reciprocal`.
