### ISSUE TITLE
Re-using the cholesky factor of the mass matrix when computing the kinetic energy of the momentum?

### ISSUE THREAD

**Issue by zoj613** [aesara-devs/aehmc#13]
https://github.com/aesara-devs/aehmc/blob/87b0c4d20c276d191522132c1f3f00fec70239b1/aehmc/metrics.py#L33-L34

It seems like we could do something like

```python
vecprod = matmul(momentum, tril_inv)
kinetic_energy = 0.5 * dot(vecprod, vecprod)
```
as an alternative. Would writing it this way cause the graph to be optimized any differently?

**Comment by rlouf** [comment]
Could you elaborate on why you think this would be a better alternative?

**Comment by zoj613** [comment]
I do not particularly think it is better. Remember, this was a question about why/when would one choose one of the either, which you recommended I turn into a github issue. So, I don't have an answer to that question. I was hoping you would let me know.

**Comment by rlouf** [comment]
I was just following the way I write the calculations by hand, never put much thought in that. I wouldn't expect the performance to be different but maybe you have a different intuition?

**Comment by zoj613** [comment]
Alright, thanks for clarifying. Closing this now.

**Comment by brandonwillard** [comment]
If it is more efficient to write it one way or another, rhat might make for a good addition to the graph optimizations.
