### ISSUE TITLE
Create a conda-forge recipe

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aehmc#17]
For better Conda compatibility, we have a conda-forge recipe waiting to be merged here: https://github.com/conda-forge/staged-recipes/pull/15767.

**Comment by rlouf** [comment]
This was merged, closing.

**Comment by brandonwillard** [comment]
> This was merged, closing.

We're still waiting for the conda-forge folks to merge https://github.com/conda-forge/staged-recipes/pull/15767.
