### ISSUE TITLE
Broadcasting issues with scalar random variables

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aehmc#26]
I am not sure this is the best repository to raise this issue, we can always transfer it to `aeppl` or `aesara` should we choose to address it there.

I was working on a very simple example for the README when I stumbled upon this issue. Consider the following:

```python
import aesara
import aesara.tensor as at
from aesara.tensor.random.utils import RandomStream
from aeppl import joint_logprob
from aehmc import hmc as hmc


Y_rv = at.random.normal(0, 1)


def logprob_fn(y):
    logprob = joint_logprob(Y_rv, {Y_rv: y})
    return logprob


# Build the transition kernel
srng = RandomStream(seed=0)
kernel = hmc.kernel(
    srng,
    logprob_fn,
    step_size=1e-3,
    inverse_mass_matrix=at.ones(1),
    num_integration_steps=10,
)

# Compile a function that updates the chain
q = Y_rv.clone()
potential_energy = -logprob_fn(q)
potential_energy_grad = aesara.grad(potential_energy, wrt=q)

next_step = kernel(q, potential_energy, potential_energy_grad)
```

which raises the following exception:

```
TypeError: Cannot convert Type TensorType(float64, (True,)) (of Variable Elemwise{add,no_inplace}.0) into Type TensorType(float64, scalar). You can try to manually convert Elemwise{add,no_inplace}.0 into a TensorType(float64, scalar).
```

The exception is raised when computing `log_prob` in the integrator. Indeed, the momentum generator returns a vector of size `1` so the updated value of `q` is no longer a scalar but a vector of size `1`.

I have tried adding `ifelse` statements so the momentum is drawn from `normal(0,1)` instead of `normal(0, 1, size=size)` but then both branches don't have the same type. How would you go about this edge case?

**Comment by brandonwillard** [comment]
> The exception is raised when computing `log_prob` in the integrator. Indeed, the momentum generator returns a vector of size `1` so the updated value of `q` is no longer a scalar but a vector of size `1`.

This sounds like this could be a design question/issue.  

For instance, should `logprob_fn` always return a something that's at least one dimensional?  If so, adding `at.atleast_1d` would fix it.  

Alternatively, should the momentum generator return a scalar?  If so, one only needs to determine why it's adding this extra dimension and fix that.

**Comment by rlouf** [comment]
I believe it would make more sense if the momentum generator returned a scalar when `inverse_mass_matrix` is a scalar. I am about to push a temporary fix; it would be nice to have:

- `shape_tuple` return an empty tuple for a scalar; `shape_tuple(1.0)` currently raises `AttributeError: 'float' object has no attribute 'ndim'`
- Something similar to `np.ndim` that returns 0 when passed a scalar.

After fixing this, I get the same `GradientDisconnectedError` as in #25.

**Comment by brandonwillard** [comment]
I believe this one is settled, so I'll close it for now.
