### ISSUE TITLE
Rename `hmc.kernel` and `nuts.kernel`

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aehmc#28]
The function name `kernel` can be misleading as this function *creates* a new kernel. We should rename it to something along the lines of `build_kernel`.

**Comment by rlouf** [comment]
To follow the convention in #29 (`new-state`) I suggest renaming `kernel` to `new_kernel`. Any objections?

**Comment by brandonwillard** [comment]
> To follow the convention in #29 (`new_state`) I suggest renaming `kernel` to `new_kernel`. Any objections?

Seems fine to me.
