### ISSUE TITLE
Add high-level API

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aehmc#60]
Currently there's a lot of code to set up the kernel etc, would be nice to wrap this into a high-level function similar to `pm.sample()`.

**Comment by rlouf** [comment]
That would be the role of a higher-level library like PyMC imo. @brandonwillard  ?

**Comment by brandonwillard** [comment]
The entry point used by the other Aesara PPL projects involves model graphs and their corresponding value variables, so we should have a similar entry point for samplers&mdash;including AeHMC's.  

We have code for such an entry point to AeHMC already (including transformations), but still need to decide how to separate/interface it with AeMCMC.  It's possible that adding such machinery here would be redundant when/if it exists in greater generality in AeMCMC, so we need to consider that first.
