### ISSUE TITLE
`ProposalStateType`, `IntegratorStateType`, etc should be `namedtuple`s

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aehmc#67]
Even if we can only pass tensors in functions used in `scan` this will make this code a lot easier to follow, and ready in case it becomes possible to pass namedtuples in `scan`.

__Originally posted by @brandonwillard in https://github.com/aesara-devs/aehmc/pull/7#discussion_r678733304__

**Comment by zoj613** [comment]
What would be attributes of a `TerminationState` tuple? @rlouf
