### ISSUE TITLE
Change the use of "optimize" to "rewrite"

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aehmc#78]
https://github.com/aesara-devs/aesara/pull/1054 in Aesara replaces the use of "optimize" with "rewrite". AeHMC will need to adapt to the API change.

**Comment by brandonwillard** [comment]
I don't think I saw any imports from the old "optimization" modules, so this might not involve any changes.

**Comment by rlouf** [comment]
`optimize_graph` is called in `utils.py`.
