### ISSUE TITLE
Set `filterwarnings` to `error` in the tests

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aehmc#79]
Our tests should not allow un-caught/checked warnings.

The addition to `setup.cfg` mentioned [here](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html) should be sufficient.  We'll need to update our tests to prevent them from failing, though.

**Comment by rlouf** [comment]
It looks like it was done in this commit: https://github.com/aesara-devs/aehmc/commit/dde2d83cf7865c8554b6accdfaad91613d36d154

I've tried only specifying `error`, and the tests fail due to a `DeprecationWarning` in `aesara`, while they pass with the current version of `setup.cfg`. Is that expected?

**Comment by brandonwillard** [comment]
> It looks like it was done in this commit: [dde2d83](https://github.com/aesara-devs/aehmc/commit/dde2d83cf7865c8554b6accdfaad91613d36d154)

Oh, yeah, this one can probably be closed then.



> I've tried only specifying `error`, and the tests fail due to a `DeprecationWarning` in `aesara`, while they pass with the current version of `setup.cfg`. Is that expected?

The current settings should make warnings emitted from within `aesara` fail.  I didn't enable all errors because some dependency was emitting a warning and it's mostly out of our control.

**Comment by rlouf** [comment]
> The current settings should make warnings emitted from within `aesara` fail. I didn't enable all errors because some dependency was emitting a warning and it's mostly out of our control.

`Aesara` imports `numpy.disutils` which in turn raises a `DeprecationWarning`, so that's probably what you saw. Otherwise sounds like a sane behavior.
