### ISSUE TITLE
Create non-trivial examples using `aeppl`'s new log-probability features

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aehmc#8]
I've just cut a new release of [`aeppl`](https://github.com/aesara-devs/aeppl) that includes the `joint_logprob` function and some basic constrained-to-unconstrained-space `RandomVariable` transforms.  We can use those to create some non-trivial examples, tests, and comparisons.

**Comment by rlouf** [comment]
#19 uses `aeppl` in combination with `aehmc` to sample from a linear regression model

**Comment by rlouf** [comment]
[This notebook(https://github.com/aesara-devs/aehmc/blob/main/examples/LinearRegression.ipynb) uses Aeppl's `joint_logprob` and a `LogTransform`.
